config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :items, except: [:new, :edit]
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
#  item model class
class Item < ApplicationRecord
  validates :text, presence: true
end

app/controllers/api/items_controller.rb
# Api module
module Api
  # Items controller class
  class ItemsController < ApplicationController
    rescue_from ActionController::ParameterMissing, with: :missing_params
    def index
      @items = Item.all
      render json: @items, status: :ok
    end

    def create
      @item = Item.new(post_params)
      respond_to do |format|
        if @item.save
          format.js
          format.json { render json: @item, status: :created }
        else
          format.json { render json: @item.errors, status: :bad_request }
        end
      end
    end

    def update
      @item = Item.find(params[:id])
      @item.update(put_params)
      respond_to do |format|
        format.js
        format.json { render json: @item, status: :ok }
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.to_s }, status: :not_found
    end

    def destroy
      @item = Item.find(params[:id])
      @item.destroy
      respond_to do |format|
        format.js {}
      end
      # TODO: research how to avoid repeating this
    rescue ActiveRecord::RecordNotFound
      head :no_content
    end

    private

    def post_params
      params.require(:item).permit(:text, :checked)
    end

    def put_params
      params.require(:item).permit(:checked)
    end

    def missing_params(exception)
      render json: { error: exception.to_s }, status: :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
# Home controller
class HomeController < ApplicationController
  def index
    @items = Item.all
    @item = Item.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>FORGET ME NOT</h1>

<%= form_with model: @item, url: api_items_path do |form| %>
 <%= form.text_field :text, class: 'item-input'%>
 <%= form.submit 'Add' %>
<% end %>
<div id="items-list">
   <%= render partial: 'api/items/item', collection: @items %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgetmenotlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>